name: "GitHub Actions Builds"

on:
  push:
  schedule:
    # Run daily
    - cron: "5 1 * * *"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup VS2019
        uses: warrenbuckley/Setup-MSBuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Add Component
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --channelId VisualStudio.16.Release --productId Microsoft.VisualStudio.Product.Enterprise -q --includeRecommended --add "Microsoft.VisualStudio.Component.VC.14.25.x86.x64"

      - name: Setup VS2019
        run: |
          dir 'C:\Program Files (x86)\Microsoft Visual Studio\2019'
          dir 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
          dir 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
          set BAZEL_VC='C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install six numpy wheel
          pip3 install keras_applications --no-deps

      - uses: actions/checkout@v2
        with:
          repository: tensorflow/tensorflow
          ref: r2.8

      - name: build whl
        run: |
          python configure.py
          bazel build -c opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
          dir
          dir bazel-bin
          dir bazel-bin\tensorflow
          dir bazel-bin\tensorflow\tools\
          dir bazel-bin\tensorflow\tools\pip_package
          dir bazel-bin\tensorflow\tools\pip_package\build_pip_package
          bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg
