name: "GitHub Actions Builds"

on:
  push:
  schedule:
    # Run daily
    - cron: "5 1 * * *"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup VS2019
        uses: warrenbuckley/Setup-MSBuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install six numpy wheel
          pip3 install keras_applications --no-deps

      - uses: actions/checkout@v2
        with:
          repository: tensorflow/tensorflow
          ref: r2.8

      - name: build whl
        run: |
          dir
          python configure.py
          bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
          bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg
